apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp
spec:
  hosts:
  - myapp
  http:
  - fault:
      delay:
        fixedDelay: 7s
        percent: 100
    route:
    - destination:
        host: myapp
        subset: v1
      weight: 95
    

    - destination:
        host: myapp
        subset: v2
      weight: 5